CONTRIBUTING.md, README.md
This PR adds a new CONTRIBUTING.md with details on how to run tests, install the package locally, and cut a release to PyPI.
=> add CONTRIBUTING guide

replicate/prediction.py
Signed-off-by: Mike Sheldon <mike@mikeasoft.com>
Currently, wait() will wait forever if a prediction is canceled by another thread/process. This PR simply adds "canceled" into the list of statuses that can end wait()
=> End wait if a prediction is canceled

CONTRIBUTING.md, replicate/client.py
This PR updates the client to look for the API's base URL in an environment variable, and default to the production host.
This will allow us to point clients at development hosts for testing.
This PR also documents the existing env vars the client supports.
Commits are significant.
=> allow API host to be configured with an env var

replicate/schema.py, replicate/version.py, tests/factories.py, tests/test_version.py
The counterpart to https://github.com/replicate/cog/pull/655
Backwards compatibility functions have been lifted from Replicate. Maybe
we should make Cog the source of truth for these...
=> Support list output

requirements-dev.txt, setup.py
In schema.py we call `from packaging import version`, which requires this package.
=> Add packaging dependency

README.md
The README has a section for pinning versions, but the code snippet is incorrect: The predict method should be called on the version, not the model.
=> fix usage for pinned versions

README.md
cc @andreasjansson @lucasmonstro
https://discord.com/channels/775512803439280149/1048368558888997007/1069599521618804786
=> document loading an output file from a URL

replicate/model.py
This PR removes the `model.predict()` method. If someone tries to call it they'll get an exception.
Normally it would make sense to deprecate stuff like this, but maybe since it's early days we can just break it.
This would be a great time to start using Semantic Versioning. We could call this 1.0.0, since it's a breaking change.
Resolves #69
=> remove model.predict()

README.md
This PR updates the README:
- Puts content in the chronological order that integrators need it: Installation, environment setup, usage...
- Adds headings so we can deep link to specific parts of the README
- Replaces the resnet image input example with [something more relevant](https://replicate.com/methexis-inc/img2prompt)
=> revamp README

README.md, replicate/__init__.py, replicate/client.py, replicate/version.py, tests/factories.py, tests/test_client.py
To be consistent with the JavaScript library. The rest of the API is only vaguely consistent, but this gets us a long way.
```python
>>> import replicate
>>> replicate.run(
"stability-ai/stable-diffusion:27b93a2413e7f36cd83da926f3656280b2931564ff050bf9575f1fdf9bcd7478",
input={"prompt": "a 19th century portrait of a wombat gentleman"}
)
['https://replicate.com/api/models/stability-ai/stable-diffusion/files/50fcac81-865d-499e-81ac-49de0cb79264/out-0.png']
```
Full examples in the README.
As an aside, I reformatted the readme to use the pretty standard Python REPL format. Shame we lost that – it made for a consistent copy & paste REPL session, and lost the syntax highlighting.
=> Add replicate.run()

replicate/prediction.py, tests/test_prediction.py
Signed-off-by: Ben Firshman <ben@firshman.com>
=> Add support for new webhooks

.github/workflows/ci.yaml, pyproject.toml, replicate/base_model.py, replicate/collection.py, replicate/files.py, replicate/json.py, replicate/model.py, replicate/prediction.py, replicate/training.py, replicate/version.py, requirements-dev.txt, tests/test_prediction.py, tests/test_version.py
Depends on #84
This PR adds [ruff](https://beta.ruff.rs/docs/) as a dev dependency to lint Python sources. It enables a handful of checks and fixes resulting violations. Additional checks like `ANN` for type annotations will be more involved, and can be taken in separate PRs.
=> Lint Python sources with ruff

replicate/training.py
Fixes a Pedantic validation error `field required (type=value_error missing)` when calling `replicate.trainings.list`.
=> Fix Pydantic validation errors for Training responses

.github/workflows/release.yaml
Resolves #81
The current release workflow builds the Python package for distribution using the following command:
```console
python -m build --sdist --outdir dist .
```
Looking at the help text for the command, the default behavior is to build both source and binary distribution. By specifying `--sdist`, we're opting out of a binary distribution, so we can remove it to opt back into that behavior. 
Going a step further, the default options use `dist` as an output directory, use the current directory as the source directory, and build source and binary distribution, which is what we're already doing. So we can get the desired behavior by running without any additional options:
```console
python -m build
```
=> Update release workflow to build source and binary distributions

replicate/client.py, tests/test_client.py
Currently, the client sends a `User-Agent` header in the form `replicate-python@<version>`. This PR changes it to `replicate-python/<version>` so that it's more in line with the standard convention [^1].
[^1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
=> Adopt `<product>/<version>` convention for `User-Agent` header

replicate/client.py
Replicate's API does not use cookies and even if we return cookies the client should not save and replay them.
=> Don't persist or send cookies to Replicate API

replicate/prediction.py
The `output` variable is shadowed by the yielding loop, so when we hit the line:
previous_output = output
the value of `output` refers to the last value of `output` from the loop above, not the total output we received. That causes the client to shrink the output down to a single string (which, inconveniently, also is a valid argument to `len()`), which means we take the wrong slice of the output the next time through the loop.
=> Fix Prediction.output_iterator

pyproject.toml
Resolves #112
[Pydantic 2.0](https://pypi.org/project/pydantic/2.0/) was released a few days ago, with breaking changes for this library.
This PR updates the dependency requirements for this package to disallow pydantic>=2. This provides a short-term fix that will be pushed out in a patch version.
In the longer term, my intention is to update this library to support both 1.x and 2.x.
=> Require pydantic 1.x

pyproject.toml, replicate/base_model.py, requirements.txt
Refs:
- https://github.com/replicate/replicate-python/issues/112
My [LLM](https://llm.datasette.io/) project uses Pydantic 2 and I want to build a plugin for it ([llm-replicate](https://github.com/simonw/llm-replicate)) that adds support for querying Replicate models - but I can't do that easily if Replicate is pinned to Pydantic 1.0.
It looks like it's possible to support both using this idiom:
```python
try:
from pydantic import v1 as pydantic
except ImportError:
import pydantic
```
Since 2.0 introduced a `v1` backwards compatibility shim.
=> Work with both Pydantic 1 and 2

pyproject.toml
Resolves #124 
This PR adds `py.typed` to the [setuptools package data](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data) for the package into `pyproject.toml`.
```toml
[tool.setuptools.package-data]
replicate = ["py.typed"]
```
My understanding is that this should denote the package as being ["typed" on PyPI](https://pypi.org/search/?c=Typing+%3A%3A+Typed).
For more information, see [PEP 561 – Distributing and Packaging Type Information](https://peps.python.org/pep-0561/#packaging-type-information).
=> Add packaging type information to `pyproject.toml`

.vscode/extensions.json, .vscode/settings.json, pyproject.toml
This PR updates the VSCode editor configuration for this project, bringing it in line with [Cog](https://github.com/replicate/cog). Once applied, contributors using VSCode will have get a common formatting and type checking behavior.
This PR also adds mypy tool configuration to `pyproject.toml` to improve the editor experience.
=> Update suggested VSCode extensions and project settings

replicate/prediction.py, tests/test_prediction.py
For more information, see https://replicate.com/docs/streaming
=> Add `stream` parameter to `predictions.create`

replicate/model.py, replicate/version.py
`Model.predict` was removed in #71. It points users to `Version.predict`, but that method was deprecated in favor of `replicate.run` in #79.
This PR updates the deprecation warnings accordingly.
=> Update deprecation warnings for `Model.predict` and `Version.predict`

replicate/prediction.py, tests/test_prediction.py
Resolves #152 
When a prediction is running, models log progress in a predictable format. By parsing these log lines, we can get a structured representation of the current number of items processed, the total number, and the percentage completed.
This PR defines a `Prediction.Progress` dataclass and a `progress` property on `Prediction` that returns an optional value of that type.
=> Add `progress` property to `Prediction`

replicate/client.py, replicate/model.py, replicate/prediction.py, replicate/version.py, tests/cassettes/test_models_get.yaml, tests/cassettes/test_models_list.yaml, tests/test_model.py
See https://replicate.com/docs/reference/http#models.get
See https://replicate.com/docs/reference/http#models.list
Currently, the `Model` class has only `username` and `name`, and the `ModelCollection.get` method constructs a new instance with the provided username and name arguments.
This PR makes the following changes to bring it more in line with the [replicate-javascript](https://github.com/replicate/replicate-javascript) and the other official clients:
- Adds `url`, `description`, `visibility`, and other fields to `Model`
- Adds `owner` field and reimplements existing `username` field to deprecated property that aliases this field
- Updates `ModelCollection.get` to fetch information about the named model from Replicate's API
- Adds `ModelCollection.list` to fetch public models from …
=> Add support for `models.get` and `models.list` endpoints

.github/workflows/ci.yaml
[Python 3.12.0](https://www.python.org/downloads/release/python-3120/) was released on October 2, 2023. This PR updates our CI to test against this version.
=> Add Python 3.12 to CI test matrix

replicate/client.py, tests/test_client.py
#147 changed some logic in how the underlying networking client is initialized. Some clients that set the `REPLICATE_API_TOKEN` environment variable after importing the `replicate` package relied on that behavior, and are now getting authentication errors (#169)
This PR restores some of the original behavior by lazily instantiating the underlying client until the first request is made. This should resolve the regression observed by users who were modifying the environment after import.
=> Lazily instantiate underlying client

.github/workflows/ci.yaml, .vscode/extensions.json, .vscode/settings.json, pyproject.toml, replicate/client.py, replicate/json.py, replicate/version.py, requirements-dev.txt
See https://docs.astral.sh/ruff/formatter/
=> Replace black with ruff format

replicate/deployment.py, replicate/prediction.py, tests/cassettes/predictions-stream.yaml, tests/test_prediction.py
Resolves https://github.com/replicate/replicate-python/issues/175
=> Fix `streaming` parameter encoding in prediction creation requests

.github/workflows/ci.yaml, pyproject.toml, replicate/base_model.py, replicate/client.py, replicate/collection.py, replicate/deployment.py, replicate/files.py, replicate/json.py, replicate/model.py, replicate/prediction.py, replicate/schema.py, replicate/training.py, replicate/version.py, requirements-dev.txt, script/format, script/lint, script/setup, script/test
See https://pylint.readthedocs.io/en/stable/
This PR also updates the project to adopt [GitHub's "Scripts to Rule Them All" convention](https://github.com/github/scripts-to-rule-them-all).
=> Configure pylint and fix linter violations

replicate/collection.py, replicate/deployment.py, replicate/model.py, replicate/prediction.py, replicate/training.py, replicate/version.py, tests/test_training.py
Provides backwards-compatible migration to typed kwargs following [PEP 692](https://peps.python.org/pep-0692/).
=> Fix signature of `create` methods

pyproject.toml, replicate/__init__.py, replicate/base_model.py, replicate/client.py, replicate/collection.py, replicate/deployment.py, replicate/exceptions.py, replicate/model.py, replicate/prediction.py, replicate/training.py, replicate/version.py, tests/test_run.py
This PR removes abstract methods from base collection, leaving each collection to define its own `get` / `create` / `list` methods on its own terms. 
The primary benefit to having abstract methods defined was to reuse shared logic for `reload`, but that method is short and required additional maneuvering to define an `id` field. The downside of this tight coupling was that resources were required to implement methods that would raise `NotImplemented`. And their signatures for `create` methods were inflexible, requiring either a mismatch with the parent class or an elaborate workaround with overloads and unpacked typed dict kwargs.
=> Refactor `Collection` superclass

README.md, replicate/__init__.py, replicate/client.py, replicate/hardware.py, replicate/model.py, tests/cassettes/hardware-list.yaml, tests/cassettes/models-create.yaml, tests/test_hardware.py, tests/test_model.py
See https://replicate.com/docs/reference/http#models.create
=> Add support for `models.create` and `hardware.list` endpoints

README.md
This PR updates the webhook example in the REAMDE with a link to Replicate's webhooks guide, plus an update to use a newer and more popular model (Kandinsky).
Resolves https://github.com/replicate/replicate-python/issues/141
=> document webhooks

replicate/collection.py, replicate/deployment.py, replicate/hardware.py, replicate/model.py, replicate/resource.py
Related to #188 
API resources define a common `id` field, which requires additional bookkeeping in `_prepare_model`. However, these fields aren't used, and either shadow a field on the resource or can be computed. This PR removes `id` from the base model, adds properties for subclasses that don't have an `id` field (like `Hardware` and `Collection`), and marks them as deprecated, for anyone who is relying on that behavior.
=> Remove `id` field from `Resource`

README.md, pyproject.toml, replicate/__init__.py, replicate/client.py, replicate/collection.py, replicate/deployment.py, replicate/hardware.py, replicate/model.py, replicate/pagination.py, replicate/prediction.py, replicate/resource.py, replicate/run.py, replicate/training.py, replicate/version.py, tests/cassettes/run-concurrently.yaml, tests/test_client.py, tests/test_collection.py, tests/test_deployment.py, tests/test_hardware.py, tests/test_model.py, tests/test_prediction.py, tests/test_run.py
This PR adds support for async operations to the Replicate client. Namespace operations like `predictions.list` and `models.create` now have async variants with the `async_` prefix (`predictions.async_list` and `models.async_create`). 
Here's an example of what that looks like in practice:
```python
model = await replicate.models.async_get("stability-ai/sdxl")
input = {
"prompt": "A chariot pulled by a team of rainbow unicorns, driven by an astronaut, dramatic lighting",
}
output = await replicate.async_run(f"stability-ai/sdxl:{model.latest_version.id}", input)
```
<details>
<summary>Output</summary>
</details>
One of the most common questions I hear is how to run a bunch of predictions in parallel. The async functionality provided by this PR makes it really …
=> Add async support

replicate/deployment.py, replicate/model.py, replicate/training.py
=> Fix import of pydantic

README.md, replicate/__init__.py, replicate/collection.py, replicate/model.py, replicate/pagination.py, replicate/prediction.py, replicate/training.py, tests/test_pagination.py
This PR adds `paginate` and `async_paginate` methods that let you iterate over a paginated list of resources.
**sync**
```python
for page in replicate.paginate(replicate.collections.list):
for collection in page:
print(collection.name)
```
**async**
```python
async for page in replicate.async_paginate(replicate.collections.async_list):
for collection in page:
print(collection.name)
```
=> Add `paginate` and `async_paginate` method

pyproject.toml, requirements-dev.txt, requirements.txt
We're relying on a feature (`deprecated`) from version 4.5.0 of typing_extensions, but the version bundled with Python varies. Include it as an explicit dependency to avoid import errors for users.
=> Add missing typing_extensions dependency

README.md, replicate/__init__.py, replicate/client.py, replicate/identifier.py, replicate/run.py, replicate/stream.py, replicate/training.py, tests/test_run.py, tests/test_stream.py
Replicate models like [meta/llama-2-70b-chat](https://replicate.com/meta/llama-2-70b-chat) support streaming output via [Server-sent Events (SSE)](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events).
This PR adds top-level `stream` and `async_stream` methods that let you iterate over tokens as they come in.
```python
tokens = []
for event in replicate.stream(
"meta/llama-2-70b-chat:02e509c789964a7ea8736978a43525956ef40397be9033abf9fd2badfe68c9e3",
input={
"prompt": "Please write a haiku about llamas.",
},
):
print(event)
tokens.append(str(event))
print("".join(tokens))
```
=> Add `stream` and `async_stream` methods to client

replicate/identifier.py, replicate/model.py, replicate/run.py, replicate/stream.py, replicate/training.py, tests/test_identifier.py
```python
for event in replicate.stream(
"meta/llama-2-70b-chat",
input={
"prompt": "Please write a haiku about llamas.",
},
):
print(str(event))
```
=> Allow `run` and `stream` methods to take model arguments, when supported

replicate/prediction.py, tests/test_stream.py
Follow-up to #204
This PR adds a `stream` method on `Prediction`. In most cases, you'll want to call `replicate.stream` to get the stream directly. But if you have an existing prediction object and want to stream its output, you can use this method instead. [^1]
[^1]: This rhymes with `run` being a shorthand for creating a prediction and calling `wait`.
=> Add `stream` method on `Prediction`

README.md
Context (https://github.com/replicate/replicate-python/pull/137): 
> Model.predict was removed in #71. It points users to Version.predict, but that method was deprecated in favor of replicate.run in #79.
Trying the example in the current iteration of `replicate/replicate-python` would return the following exception:
```python
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Version' object has no attribute 'predict'
```
=> Update README example from `version.predict`

replicate/prediction.py, replicate/run.py
Use non blocking wait function
=> Add async_wait method to Prediction class

.vscode/settings.json, replicate/client.py, replicate/prediction.py, replicate/run.py
=> Update `async_run` to use async output iterator

README.md, replicate/prediction.py, replicate/training.py, tests/test_prediction.py, tests/test_training.py
This PR improves the experience of using Replicate's [training APIs](https://replicate.com/docs/reference/http#trainings.create) by making the following changes:
- Adding a section to the README discussing how to create a training
- Updating the `Training.cancel` instance method to mutate the caller, matching the behavior of `prediction.reload`
- Adding test coverage for async variants of training namespace methods
This PR also makes corresponding changes to predictions APIs to fix a few discrepancies that were found along the way.
=> Document fine-tuning and clean up trainings API

replicate/version.py, tests/test_version.py
In https://github.com/replicate/replicate-python/issues/173, @satellitebryn mentioned the [`models.versions.delete`](https://replicate.com/docs/reference/http#models.versions.delete) endpoint, which currently doesn't have a corresponding method in the Python client.
This PR adds a `delete` and `async_delete` method to the `versions` namespace.
```python
model = client.models.get("your-username/model-name")
model.versions.delete(model.latest_version.id)
```
=> Implement `models.versions.delete` endpoint

README.md
Update sign-off prior commit in git history (https://github.com/replicate/replicate-python/commit/cd09db0691a96c3c299e1f9ac374d420bb4adbdd) + Add basic base64 example
=> Update README to provide instructions for base64-encoding image inputs

README.md
This tries to improve our current situation where our language models do not include the version string by calling out this discrepancy and giving an example of a language model input.
=> Clarify model identifier in README

replicate/client.py, replicate/exceptions.py, tests/test_client.py
Related to #261 
This PR improves the `ReplicateError` type by having it conform to the problem details response as defined in RFC 7807.
=> Improve client HTTP errors

replicate/account.py, replicate/deployment.py, tests/test_deployment.py
Alternative to #247 
See https://replicate.com/docs/reference/http
=> Add support for deployments endpoints

replicate/client.py, tests/test_client.py
`Client.__init__`  takes a `**kwargs` argument that gets passed to the underlying httpx client constructor. However, the current implementation doesn't honor any custom headers that are passed. This PR fixes that.
=> Apply custom headers passed to client constructor

.github/workflows/ci.yaml, README.md, replicate/prediction.py, tests/test_stream.py
A few folks have expressed confusion about how to stream output from a prediction. This PR updates the README with documentation and adds a missing `async_stream` instance method on `prediction`.
=> Improve ergonomics of streaming predictions

replicate/deployment.py, tests/test_deployment.py
#258 added fields to the `Deployment` model provided by the new `deployments.{get,list,update}` endpoints. However, those were implemented against a version of the OpenAPI specification that disagreed with the actual API responses. Specifically, the `min_instances` and `max_instances` properties were listed as subproperties of a `scaling` object rather than direct fields. The result — as reported in #270 — was Pydantic validation errors like this:
```
raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Deployment
current_release -> configuration -> scaling
field required (type=value_error.missing)"
```
This PR updates the `Deployment` model to correctly locate `min_instances` and `max_instances` as properties of `current_release.configuration`.
=> Fix `Deployment` model definition

replicate/stream.py
Fixes #287 
Given the following code:
```python
def go():
for event in replicate.stream(
"meta/meta-llama-3-8b-instruct",
input={
"top_p": 0.9,
"prompt": "Hi! Help me please:)",
"max_tokens": 512,
"min_tokens": 0,
"temperature": 0.01,
"stop_sequences": "<|end_of_text|>",
"prompt_template": "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n",
"presence_penalty": 0,
"frequency_penalty": 1,
},
):
print(str(event), end="")
print()
go()
print("---------------------------------")
go()
print("---------------------------------")
go()
print("---------------------------------")
```
The latest release repeats the same token …
=> Fix initialization of stream decoder

replicate/client.py, tests/test_client.py
Replicate's API now supports the standard [Bearer authentication scheme](https://swagger.io/docs/specification/authentication/bearer-authentication/). 
https://replicate.com/changelog/2024-04-03-bearer-tokens
For compatibility with existing clients, the existing `Token` scheme will be supported indefinitely. But going forward, the new `Bearer` scheme is preferred.
=> Use Bearer authorization scheme

replicate/training.py, tests/test_training.py
=> Populate training destinations from output

tests/test_stream.py
=> Skip streaming integration tests if `REPLICATE_API_TOKEN` isn't set

replicate/client.py
The response is closed synchronously in the async path, unnecessarily blocking.
The PR closes the response asynchronously instead
=> asynchronously close of response

README.md, replicate/model.py
Add overloads to pass model owner and name as distinct arguments or as a single string.
=> Improve support for `models.get` and `models.delete` endpoints

README.md
=> Reorganize and reword discussion of streaming language models

replicate/client.py, replicate/webhook.py, tests/test_webhooks.py
=> Add support for validating webhooks

replicate/__init__.py, tests/test_webhooks.py
=> Export webhooks namespace to default client

README.md, replicate/exceptions.py, replicate/prediction.py, replicate/run.py, tests/test_run.py
This PR extends #325 to add the prediction object itself to `ModelError`, as opposed to just its ID. This makes it convenient to introspect logs and other information to determine how to handle the failure.
```python
from replicate.exceptions import ModelError
try:
output = replicate.run("stability-ai/stable-diffusion-3", { "prompt": "..." })
except ModelError as e
if "(some known issue)" in e.logs:
pass
print("Failed prediction: " + e.prediction.id)
```
=> Add `prediction` field to `ModelError`

pyproject.toml, replicate/webhook.py
Resolves CI failure due to new linter violations in latest version of Rye: https://github.com/replicate/replicate-python/actions/runs/10100187511/job/27930960051
=> Fix linting errors

.vscode/settings.json, replicate/file.py, tests/test_file.py
Resolves #338 
Follow up to #226 
Filenames from open file handles were not being passed correctly in `create` / `async_create`. This PR fixes that and adds some test coverage.
=> Correctly pass filename to file creation call

replicate/deployment.py, replicate/file.py, replicate/model.py
Resolves #356 
When deleting a model, Replicate's API returns with a 204 and an empty response body. The client library fails to decode this and raises and exception.
This PR updates the `replicate.models.delete` method to return `bool` instead to indicate success. It also harmonizes the other delete methods for deployments and files to do the same.
=> Consistently return Boolean for delete methods

pyproject.toml, replicate/client.py, replicate/prediction.py, replicate/run.py, replicate/stream.py, tests/test_run.py
This PR introduces a new beta branch which will default to providing FileOutputs for all calls to `replicate.run()` as well as defaulting to using the blocking API.
The intention is to publish `1.0.0b1` to PyPi using the `beta` branch that will mirror `main`.
=> Switch to using file outputs and blocking api by default

replicate/client.py, replicate/prediction.py, replicate/run.py, replicate/stream.py, tests/test_run.py
I meant to ship https://github.com/replicate/replicate-python/pull/364 as 1.0.0, but cut the release without landing it on the main branch. Whoops.
=> 1.0.1 candidate

replicate/deployment.py, replicate/model.py, replicate/prediction.py
This fixes a bug in the new `wait` implementation where the default read timeout for the HTTP client is shorter than the timeout on the server. This results in the client erroring before the server has had the opportunity to respond with a partial prediction.
This commit now provides a custom timeout for the `predictions.create` request based on the `wait` parameter provided. We add a 500ms buffer to the timeout to account for some discrepancy between server and client timings.
I attempted to try and refactor the shared code between models, deployments & predictions but gave up. We now have a single function that creates the `headers` and `timeout` params and passes them in at the various call sites.
=> Configure read timeout based on `wait` parameter

replicate/run.py, tests/test_run.py
Prior to 1.0.0 `replicate.run()` would return an iterator for cog models that output a type of `Iterator[Any]`. This would poll the `predictions.get` endpoint for the in progress prediction and yield any new output.
When implementing the new file interface we introduced two bugs:
1. The iterator didn't convert URLs returned by the model into `FileOutput` types making it inconsistent with the non-iterator interface. This is controlled by the `use_file_outputs` argument.
2. The iterator was returned without checking if we are using the new blocking API introduced by default and controlled by the `wait` argument.
This commit fixes these two issues, consistently applying the `transform_output` function to the output of the iterator as well as returning the polling iterator …
=> Fix iterator support for replicate.run()

README.md
This commit incorporates the changes from #386 as well as removing mention of the data URLs added in 86c5e14.
=> Remove mention of data URLs from README

replicate/helpers.py, tests/test_run.py
This commit adds tests for the `file_encoding_strategy` argument for `replicate.run()` and fixes two bugs that surfaced:
1. `replicate.run()` would convert the file provided into base64 encoded data but not a valid data URL. We now use the `base64_encode_file` function used for outputs.
2. `replicate.async_run()` accepted but did not use the `file_encoding_strategy` flag at all. This is fixed, though it is worth noting that `base64_encode_file` is not optimized for async workflows and will block. This might be okay as the file sizes expected for data URL payloads should be very small.
=> Fix a couple of bugs in the base64 file_encoding_strategy

README.md, replicate/client.py, replicate/helpers.py, replicate/run.py, tests/test_client.py
This PR introduces support for the cog context introduced in 0.14.11 into the Replicate SDK. The `current_scope` helper now makes per-prediction context available via the `current_scope().context` dict.
A cog model can then provide a `REPLICATE_API_TOKEN` on a per-prediction basis to be used by the model.
```
curl -X POST http://localhost/predictions -H 'Content-Type: application/json' -d '{
"inputs": { "prompt": "make me a sandwich" },
"context": { "REPLICATE_API_TOKEN": "r8_xyz..." }
}'
```
```py
def predict(prompt: str) -> str:
replicate = Replicate()
output = replicate.run("anthropic/claude-3.5-haiku", {input:
{"prompt": "prompt"}})
return output
```
=> Read REPLICATE_API_TOKEN from cog context
