replicate/replicate-python

- replicate/client.py
- replicate/exceptions.py
- replicate/prediction.py
- replicate/version.py
- tests/factories.py
- tests/test_prediction.py
- tests/test_version.py
A few fixes in here for raising better errors.
> Better errors!

- README.md
- replicate/version.py
> Document pinning to versions

- replicate/client.py
This is primarily for iterating through `predict()`, where if an
exception is thrown the client has no way of restarting the iterator.
> Retry GET requests

- replicate/prediction.py
- tests/test_prediction.py
> Add webhook_completed to prediction

- README.md
> Add better example with stable diffusion

- README.md
> Recommend pinning

- README.md
This is a yucky API but it's better than breaking everyone's stuff.
> Pin everything to a version

- replicate/client.py
Signed-off-by: Ben Firshman <ben@firshman.com>
> Don't retry 500 responses for requests that mutate data

- replicate/training.py
- tests/test_training.py
See https://replicate.com/docs/reference/http#trainings.list
> Add support for `trainings.list` endpoint

- README.md
Signed-off-by: Charlie Holtz <charlie@replicate.com>
> Update README.md to include colab link

- replicate/prediction.py
- tests/test_prediction.py
> Add `metrics` field to `Prediction`

- README.md
> Indicate Python requirements in README

- .vscode/extensions.json
- .vscode/settings.json
See https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions
> Update VSCode settings for Python Tools

- replicate/client.py
- tests/cassettes/test_run_without_token.yaml
- tests/test_run.py
> Don't set Authorization header unless API token is provided

- README.md
- replicate/stream.py
Resolves #213 
This PR fixes a few bugs in the streaming implementation added with #204.
> Fix `stream` functionality

- pyproject.toml
quick fix to #233 , should someone else run into it again. not at all urgent but a nice quality of life deal.
> now with accurate pydantic version

- replicate/exceptions.py
> Fix linter warnings in `exceptions.py`

- tests/test_stream.py
> Update integration tests to catch 401 errors

- replicate/deployment.py
- tests/test_deployment.py
> Add support for `deployments.delete` endpoint

- README.md
> Update README, add missing `"`

- README.md
> fix syntax error in readme snippet
